#!/usr/bin/env bash
# Container entrypoint. Starts sshd and stays alive.
#
# Both halves matter on RunPod. A pod whose container process exits is a pod that stops, so
# `CMD ["/bin/bash"]` -- fine for `docker run -it` -- terminates the instant it starts with no
# TTY attached, and the rental dies before you can look at it. And RunPod's SSH access needs
# a real sshd listening on 22 inside the container; the web terminal goes through their agent,
# but `ssh` and `scp` (which is how the ~1 GB bundle arrives) do not.
#
# RunPod's documented recipe installs openssh-server at pod start. That is ~20 s of billed
# time, a network dependency at the worst moment, and an apt repo that has to be up. It is
# baked into the image instead; this script only does the parts that need the pod's own
# environment.
set -euo pipefail

# RunPod injects the account's public key here. Absent on a plain `docker run`, which is fine:
# that path uses `docker exec`, not ssh.
if [ -n "${PUBLIC_KEY:-}" ]; then
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    echo "$PUBLIC_KEY" >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
fi

# Materialise the image's ENV for ssh sessions.
#
# THIS IS NOT REDUNDANT WITH THE DOCKERFILE'S `ENV` LINES. Docker hands those to the container's
# entrypoint -- this script -- and to anything it spawns, including sshd. But **sshd does not
# pass its own environment on to user sessions**: it builds a fresh one per session from
# /etc/login.defs, PAM and the shell's startup files. So `docker exec` sees HF_HOME and an ssh
# session does not, and on RunPod every human and every script arrives over ssh.
#
# Measured on an A100 pod, 2026-09-19, with all three ENV lines present in the image:
#
#   $ ssh runpod 'env | grep -i hf_'      -> (nothing)
#   $ ssh runpod 'bash /opt/app/preflight.sh'
#       FAIL  CUDA toolkit reachable: nvcc not on PATH
#       FAIL  flashinfer sampler off: VLLM_USE_FLASHINFER_SAMPLER is None, expected '0'
#
# and vllm re-downloaded the 2.65 GB checkpoint the image had already baked, on billed time,
# because HF_HOME was unset so the default ~/.cache/huggingface applied.
#
# Written from the live values rather than hardcoded, so this cannot drift from the Dockerfile.
# Both files are needed: /etc/profile.d is read by login shells (`ssh host`, tmux panes), while
# `ssh host 'cmd'` runs a non-login shell that reads only ~/.bashrc.
{
    echo "# Generated by start.sh: the image ENV that sshd would otherwise drop."
    for var in HF_HOME HF_HUB_ENABLE_HF_TRANSFER CUDA_HOME VLLM_USE_FLASHINFER_SAMPLER \
               PYTHONUNBUFFERED UV_COMPILE_BYTECODE UV_LINK_MODE; do
        [ -n "${!var:-}" ] && printf 'export %s=%q\n' "$var" "${!var}"
    done
    printf 'export PATH=%q\n' "$PATH"
} > /etc/profile.d/glm-ocr-env.sh
chmod 0644 /etc/profile.d/glm-ocr-env.sh

# ~/.bashrc is what `ssh host 'command'` reads; without this the non-interactive path -- which
# is how every script and every CI-ish invocation arrives -- still gets nothing.
grep -qF 'glm-ocr-env.sh' /root/.bashrc 2>/dev/null \
    || echo '. /etc/profile.d/glm-ocr-env.sh' >> /root/.bashrc

# Host keys are generated here rather than baked: an image-wide host key would be shared by
# every pod anyone ever launches from it, which is both a warning on every connection and a
# genuine impersonation risk on a public image.
ssh-keygen -A
mkdir -p /run/sshd
/usr/sbin/sshd -D -e &

echo "glm-ocr-hu-env ready. Next: bash /opt/app/preflight.sh"

# Keep the container alive. `wait` rather than `sleep infinity` so a dying sshd surfaces
# instead of leaving a pod that looks healthy and refuses every connection.
wait -n
